### ISSUE TITLE
Redux Saga is not supported

### ISSUE THREAD

**Issue by jandramila** [hindmost/reduxed-chrome-storage#6] opened 2021-09-08 01:32 UTC
Hello there, I really like this library and I'm considering using it on a production environment, I've already stared it!

I'm having certain issues with Redux Saga middleware, this is my setup on async background script:

```js
const sagaMiddleware = createSagaMiddleware();
const middleware = [sagaMiddleware];

if (process.env.NODE_ENV !== "production") {
  const logger = createLogger({
    diff: true,
  });
  middleware.push(logger);
}

const store = await storeCreatorFactory({ createStore })(
  rootReducer,
  applyMiddleware(...middleware)
);
sagaMiddleware.run(rootSaga);
```

Then on my Sagas, when trying to do `yield select` I'm getting the initial state, A.K.A. the object returning from the initial store's `getState`.

I'm sharing an example of what is happening using `redux-logger` middleware to output current state (which does seem to work) and then logging from inside a saga using `yield select` to get current state from that saga's perspective.

![image](https://user-images.githubusercontent.com/10802091/132431429-fcbd0475-abdd-4e78-8e11-552116e981c8.png)

Thank you for this and keep up with the good work!

**Comment by jandramila** [comment] 2021-09-08 03:12
I've found an intricate workaround using `runSaga` API and custom channel / middleware, it seems like default saga middleware is tightly coupled to initial store object, thus loosing access to fresh `getState` method when trying to do `yield select`.

Here is what I've done:

`setupSaga`
```js
import { stdChannel } from "redux-saga";

function setupSaga() {
  const channel = stdChannel();
  const sagaMiddleware = () => (next) => (action) => {
    const result = next(action);
    channel.put(action);
    return result;
  };

  return { channel, sagaMiddleware };
}
```


`background.js`
```js
  const { channel, sagaMiddleware } = setupSaga();
  const middleware = [sagaMiddleware];

  if (process.env.NODE_ENV !== "production") {
    const logger = createLogger({
      diff: true,
    });
    middleware.push(logger);
  }

  const store = await storeCreatorFactory({ createStore })(
    rootReducer,
    applyMiddleware(...middleware)
  );

  // Run sagas using custom channel to overcome async reduxed store problems
  runSaga(
    {
      channel,
      dispatch: store.dispatch,
      getState: () => store.getState(),
    },
    rootSaga
  );
```

This pretty much feels like monkey patching as I'm trying to replicate default behavior.

Hope it helps until fixed!

**Comment by hindmost** [comment] 2021-09-08 18:15
Sorry but as of now it's unclear what exactly your problem is.
You have to provide more details enough to understand your problem, otherwise I have to close this issue. Ideally you create a minimal, reproducible example like it's described [here](https://stackoverflow.com/help/minimal-reproducible-example). And please, DO NOT post images of code/output etc.

BTW, you could star this repo if you really like it.

**Comment by hindmost** [comment] 2021-09-10 08:48
So I close this issue until you provide a reproducible example. I suggest to make it as a couple of Mocha tests supposed to do the same using my library and original Redux respectively. If the results are different, it'd be a proof of real issue (otherwise it'd prove the contrary). You can use [this test](https://github.com/hindmost/reduxed-chrome-storage/blob/master/test/async-actions.ts) as a sample.

**Comment by nopol10** [comment] 2022-01-16 14:04
On the topic of `redux-saga`, I'd also like to add that if anyone happens to be using `redux-saga-thunk`, this patch to that package's `middleware.js` needs to be made to get it to work with `reduxed-chrome-storage` due to the store being recreated during runtime:

```diff
diff --git a/node_modules/redux-saga-thunk/dist/middleware.js b/node_modules/redux-saga-thunk/dist/middleware.js
index 343b654..3127502 100644
--- a/node_modules/redux-saga-thunk/dist/middleware.js
+++ b/node_modules/redux-saga-thunk/dist/middleware.js
@@ -6,9 +6,8 @@ Object.defineProperty(exports, "__esModule", {
 
 var _utils = require('./utils');
 
+var responses = {};
 var middleware = function middleware() {
-  var responses = {};
-
   return function (next) {
     return function (action) {
       var error = action.error,
```

**Comment by hindmost** [comment] 2022-10-13 15:07
Hello @nopol10. Recently I released a [new major version](https://github.com/hindmost/reduxed-chrome-storage/releases/tag/3.0.10) of this library. The OP seems to be unresponsive. That's why I ask you: could you please check if this problem still exists with the new version? And if so, could you make a minimal extension example that reproduces the problem?

**Closed as completed** 2022-10-24 14:17 UTC
